// This file is automatically generated by build.rs

// pub const APP_API_URL: &'static str = "127.0.0.1:8888";
pub const APP_API_URL: &'static str = "localhost:9999";
// pub const APP_API_URL: &'static str = "192.168.0.23:8888";
pub const APP_CSRF_TOKEN: &'static str = "dWx0cmEtaW5zdGluY3QtZ29rdQ==";
