version: '0.1'
name: ${PROJECT}

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}_client
    restart: always
    networks:
      - network
    env_file:
      - .env.prod
    security_opt:
      - no-new-privileges:true

networks:
  network:
    name: ${PROJECT}_network
    external: true
