version: '3.9'
name: ${PROJECT}

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}_admin
    restart: always
    networks:
      - external_network
    env_file:
      - .env.prod
    security_opt:
      - no-new-privileges:true

networks:
  external_network:
    name: ${PROJECT}_network
    external: true
