[application]

[web.app]

# HTML title tag content
title = "admin-dioxus"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["src", "assets"]

[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.wasm_opt]
level = "z"
