version: "0.1"
name: ${PROJECT}

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}_admin
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - network
    env_file:
      - .env.docker
    security_opt:
      - no-new-privileges:true
    # volumes:
    #   - ./src

networks:
  network:
    name: ${PROJECT}_network
    external: true